### ISSUE TITLE
Any chance of .net version update?

### ISSUE THREAD

**Issue by yevvie** [thatshaman/tilegenerator#1]
This would be really handy for slicing up my own custom maps for Leaflet use, but having to use a non supported/EoL'd version of .net is something I'd like to avoid. No pressure to do so at all, just wanted to ask if there was a possibility of it.

**Comment by thatshaman** [comment]
Have upgraded both the source and latest release to .net 8.0 and I've also upgraded the packages to the latest version

**Comment by yevvie** [comment]
Awesome, thanks a ton
